allauth/urls.py
from django.conf.urls import url, include
from allauth.compat import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.package + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

housing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main.views import home, AptComplexDetailView, AptListingDetailView, ListingCreateView
from django.conf import settings 


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^$', 'main.views.home'),
	#url(r'^complex/$','main.views.appartment_complex'),
	url(r'^complex/(?P<pk>\d+)/$', AptComplexDetailView.as_view()),
	url(r'^listing/(?P<pk>\d+)/$', AptListingDetailView.as_view()),
	url(r'^listingcreate/$', ListingCreateView.as_view()),
	url(r'^housing_api/', 'main.views.housing_API_view'),
	url(r'^media/(?P<path>.*)/$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^single_complex/(?P<pk>\d+)/$', 'main.views.list_units_in_complex'),
	url(r'^accounts/$', 'main.views.home'),
	url(r'^accounts/', include('allauth.urls')),
]

main/models.py
from __future__ import unicode_literals
from django.db import models
from housing.local_settings import local_GoogleAPI_key
from django.core.urlresolvers import reverse

import googlemaps

class Listing(models.Model):
	name = models.CharField(max_length=70)

	roommates = models.IntegerField()

	availability_date = models.DateField()

	MALE = 'M'
	FEMALE = 'F'
	OTHER = 'Other'
	GENDER_CHOICES = (
		(MALE, 'Male'),
		(FEMALE, 'Female'),
		(OTHER, 'Other'),
		)
	gender_choices = models.CharField(max_length=5, choices=GENDER_CHOICES, default=MALE)

	SHARED = 'Shared'
	PRIVATE = 'Private'
	MARRIED = 'Married'
	ROOM_TYPE = (
		(SHARED, 'Shared'),
		(PRIVATE, 'Private'),
		(MARRIED, 'Married'),
		)
	room_type = models.CharField(max_length=7, choices=ROOM_TYPE, default=PRIVATE)

	FURNISHED = 'Furnished' 
	PARTIAL_FURNISHED = 'Partial Furnished' 
	UNFURNISHED = 'Unfurnished' 
	FURNISHINGS = (
		(FURNISHED,'Furnished'),
		(PARTIAL_FURNISHED, 'Partial Furnished'),
		(UNFURNISHED, 'Unfurnished'),
		) 
	furnishings_type = models.CharField(max_length=20, choices=FURNISHINGS, default=UNFURNISHED) 

	FALL = 'Fall'
	SUMMER = 'Summer'
	WINTER = 'Winter'
	FALL_WINTER = 'Fall/Winter'
	WINTER_SUMMER = 'Winter/Summer'
	SUMMER_FALL = 'Summer/Fall'
	FULL_YEAR = 'Full Year'
	OTHER = 'Other'
	CONTRACT_LENGTH = (
		(FALL, 'Fall'),
		(SUMMER, 'Summer'),
		(WINTER, 'Winter'),
		(FALL_WINTER, 'Fall/Winter'),
		(WINTER_SUMMER, 'Winter/Summer'),
		(SUMMER_FALL, 'Summer/Fall'),
		(FULL_YEAR, 'Full Year'),
		(OTHER, 'Other'),
		)
	contract_length = models.CharField(max_length=15, choices=CONTRACT_LENGTH, default=FALL_WINTER)
	
	APARTMENT = 'Apt'
	HOUSE = 'House'
	BUILDING_TYPE = (
		(APARTMENT, 'Apartment'),
		(HOUSE, 'House'),
		)
	building_type = models.CharField(max_length=10, choices=BUILDING_TYPE, default=APARTMENT)
	
	BYU_housing = models.BooleanField(default=False)


	amenity = models.ManyToManyField('Amenities', blank=True)

	apartment_complex = models.BooleanField(default=True)

	complex_name = models.ForeignKey('ComplexName', blank=True, null=True)

	distance_from_BYU = models.FloatField(null=True, blank=True, editable=False)

	distance_from_UVU = models.FloatField(null=True, blank=True, editable=False)

	address = models.CharField(max_length=70, null=True, blank=True)

	apt_number = models.CharField(max_length=20,null=True, blank=True, verbose_name='Apt/Suite #')

	city = models.CharField(max_length=70, null=True, blank=True)

	state = models.CharField(max_length=70, null=True, blank=True)

	selling_price = models.IntegerField()

	description = models.TextField()

	upload_image = models.ImageField(upload_to='media',null=True, blank=True)

	deposit = models.CharField(max_length=70, null=True, blank=True)

	creation_date = models.DateField(auto_now=True)

	latitude = models.FloatField(null=True, blank=True, editable=False)
	longitude = models.FloatField(null=True, blank=True, editable=False)

	def __unicode__(self):
		return self.address

	def save(self):
		if not self.address:
			complex_address = self.complex_name.address 
			full_address = "%s %s" % (complex_address, "USA")
		else:
			full_address = "%s %s %s %s" % (self.address,self.city,self.state,"USA")


		gmaps = googlemaps.Client(key=local_GoogleAPI_key)
		latlng = gmaps.geocode(full_address)
		print "88888"
		print latlng
		print "88888"
		self.latitude = latlng[0]['geometry']['location']['lat'] 
		self.longitude = latlng[0]['geometry']['location']['lng'] 
		print self.longitude
	
		googleAPI_dict_BYU = gmaps.distance_matrix((full_address), "Brigham Young University, Provo, UT 84602" )
		googleAPI_dict_UVU = gmaps.distance_matrix((full_address), "Utah Valley University, 800 West University Parkway, Orem, UT 84058" )


		tempBYU = (googleAPI_dict_BYU['rows'][0]['elements'][0]['distance']['text']) #from google API
		tempUVU = (googleAPI_dict_UVU['rows'][0]['elements'][0]['distance']['text'])
		
		def str_to_miles_convert(temp1):
			temp1 = temp1.split() #temp1's form: '413 km' as example
			dist_in_miles = round((float(temp1[0])*.621371), 1)
			return dist_in_miles


		self.distance_from_BYU = str_to_miles_convert(tempBYU)
		print "dist %d" % self.distance_from_BYU
		self.distance_from_UVU = str_to_miles_convert(tempUVU)


		super(Listing, self).save()

	def get_absolute_url(self):
		return reverse('main.views.home')

	

class Amenities(models.Model):
	amenity = models.CharField(max_length=20)

	def __unicode__(self):
		return self.amenity

	class Meta:
		verbose_name_plural = 'amenities'

class ComplexName(models.Model):
	name = models.CharField(max_length=40)
	address = models.CharField(max_length=150)
	latitude = models.FloatField(null=True, blank=True)
	longitude = models.FloatField(null=True, blank=True)
	website = models.CharField(max_length=70, null=True, blank=True)
	phone_number = models.CharField(max_length=20, null=True, blank=True)


	def __unicode__(self):
		return self.name

main/forms.py
from django import forms
from .models import Listing
from datetimewidget.widgets import DateWidget


class ListingForm(forms.ModelForm):
	class Meta:
		model = Listing
		widgets = {'availability_date':DateWidget(attrs={'id':"yourdateid"}, usel10n = True, bootstrap_version=3)}
		fields = ['name', 'roommates', 'availability_date', 'gender_choices','room_type', 'furnishings_type', 'contract_length', 'building_type', 'BYU_housing', 'amenity', 'apartment_complex', 'complex_name', 'address', 'apt_number', 'city', 'state', 'selling_price', 'description', 'deposit', 'upload_image']
		

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView
from django.core import serializers
from django.http import HttpResponse
from itertools import chain

from .models import ComplexName, Listing
from .forms import ListingForm


#class Testing(TemplateView):
#   template_name = "testing.html"

def housing_API_view(request):
	request.method == 'POST'

	complexes = ComplexName.objects.all()
	listings = Listing.objects.filter(apartment_complex=False)
	joined_collection = list(chain(complexes, listings))

	json = serializers.serialize('json', joined_collection,)
	# complex_output = serializers.serialize('json', complexes, fields=('name', 'address'))
	# listings_output = serializers.serialize('json', listings, fields=('name', 'address', 'city', 'state'))

	output = json

	return HttpResponse(output, content_type='application/json')





def list_units_in_complex(request, pk):
	print "pk %s: " % pk
	listings = Listing.objects.filter(complex_name=pk)
	complexname = ComplexName.objects.get(pk=pk)
	context={}

	print"listings: %s" % listings

	context['complex'] = complexname
	context['listings'] = listings


	return render(request, 'list_detail.html', context)




def home(request):
	complex_name = ComplexName.objects.all()
	house_listings = Listing.objects.filter(apartment_complex=False)

	context = {}

	context['complex_list'] = complex_name
	context['house_list'] = house_listings

	print "house list %s" % context['house_list']
	print "complex list %s" % context['complex_list']


	return render(request, 'both_list_views.html', context)


class AptComplexDetailView(DetailView):
	model = ComplexName
	template_name = "both_list_views.html"
	context_object_name = "complex"


class AptListingDetailView(DetailView):
	model = Listing
	template_name = "detail_view.html"
	context_object_name = "listing"



class ListingCreateView(CreateView):
    form_class = ListingForm
    template_name = "post.html"

main/templates/base 2.html
<!DOCTYPE html>
<html>

<head>
	<title>
		{% block head_title %}
		{% endblock %}
	</title>
	{% block extra_head %} 
	{% endblock %}
</head>

<body>
	{% block header %} 
	{% endblock %} 
	{% block body %} 
	<div class="container-fluid">
	<div class="row clearfix">
		<div class="top">
			<h2 id="title">Provo Housing Database</h2>

	
				<div class='col-md-offset-9'>
						{% if user.is_authenticated %}
							<a href="/" class="btn btn-primary">Home</a>
							<a class="btn btn-primary" href="{% url 'account_logout' %}">Sign Out</a>
							<a href="/listingcreate" class="btn btn-primary">Post a Listing</a>
				
						{% else %}
						<a href="/" class="btn btn-primary">Home</a>
						<a class="btn btn-primary" href="{% url 'account_login' %}">Sign In</a>
						<a class="btn btn-primary" href="{% url 'account_signup' %}">Sign Up</a>
						{% endif %}

				</div>
			</div>
		<div class="spacer"></div>
	{% block content %} {% endblock %} {% endblock %} {% block extra_body %} {% endblock %}
</body>

</html>

main/templates/base.html
{% extends "base 2.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
{% block extra_head %}

	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
	<meta charset="utf-8">

	<title>Places Searchbox</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


	<link rel="stylesheet" type="text/css" href=" {% static 'css/base.css' %} ">


{% endblock %}

<body>
{% block header %}
	<script> <!-- facebook code -->
	  window.fbAsyncInit = function() {
		FB.init({
		  appId      : '891354204306437',
		  xfbml      : true,
		  version    : 'v2.5'
		});
	  };

	  (function(d, s, id){
		 var js, fjs = d.getElementsByTagName(s)[0];
		 if (d.getElementById(id)) {return;}
		 js = d.createElement(s); js.id = id;
		 js.src = "//connect.facebook.net/en_US/sdk.js";
		 fjs.parentNode.insertBefore(js, fjs);
	   }(document, 'script', 'facebook-jssdk'));
	</script>  <!-- end facebook code -->




		


		</div>
{% endblock %}
{% block content %}
	



			
		{% block mainblock %}
		
		
		{% endblock mainblock %}


	</div>

<input id="pac-input" class="controls" type="text" placeholder="Search Box">

</div>
{% endblock %}
</body>

</html>

main/templates/both_list_views.html
{% extends "base.html" %}
{% load staticfiles %}

{% block mainblock %}

<div class="row">


		<div class="col-xs-2">
			
			<div id="filters">
				<input id="search" class="search" placeholder="Search" />

			<ul>Distance to BYU</ul>
			  
			  <input type="range" min="0" max="25" value="1" onchange=""/>
			  <span id="range"></span>


			<ul>Distance to UVU</ul>
			  <input type="range" min="0" max="25" value="1"/>
			<ul>Price Range</ul>
			  <input type="range" min="50" max="2500" value="300"/>
			<ul># of Roommates</ul>
			  <input type="range" min="0" max="25" value="1"/>
			<ul>Roommate Gender</ul>
			  <form>
			    <input type="checkbox"  value="male"> Male<br>
				<input type="checkbox"  value="female"> Female <br>
				<input type="checkbox"  value="mixed"> Mixed
			  </form>
			<ul>Shared/Private</ul>
			<form>
			    <input type="checkbox"  value="private"> Private<br>
				<input type="checkbox"  value="shared"> Shared
			  </form>
			<ul>Contract Length</ul>
			<form>
			    <input type="checkbox"  value="fall/winter"> Fall/Winter <br>
				<input type="checkbox"  value="full year"> Full Year <br>
				<input type="checkbox"  value="winter/summer"> Winter/Summer <br>
				<input type="checkbox"  value="summer/fall"> Summer/Fall <br>
				<input type="checkbox"  value="fall"> Fall <br>
				<input type="checkbox"  value="summer"> Summer <br>
				<input type="checkbox"  value="winter"> Winter <br>
				<input type="checkbox"  value="no contract"> No Contract <br>
				<input type="checkbox"  value="other"> Other
			  </form>
			<ul>Furnished</ul>
			<form>
			    <input type="checkbox"  value="furnished"> Furnished<br>
				<input type="checkbox"  value="not furnished"> Partially Furnished<br>
				<input type="checkbox"  value="not furnished"> Not Furnished
			</form>
			<ul>Availability Date</ul>
			<form>
				<input type="checkbox"  value="available now"> Available Now<br>
			</form>
			<ul>Apt/House</ul>
			<form>
			    <input type="checkbox"  value="apartment"> Apartment<br>
				<input type="checkbox"  value="house"> House
			  </form>
        
		</div>

		</div>


<div class="sidebars">
<div class="col-xs-9">
	<div class="row tabs">
		<div class="col-xs-6 map">
			<p>Map View</p>
		</div>
		<div class="col-xs-6 list">
			<p>List View</p>
		</div>
	</div>

	
	<div id="listview" class="row lists">
		<div class="col-xs-6"><!-- house list -->
			<div class="row">
				<div class="col-sm-12">
					<div class="row border">
						
						<img src=" {% static 'home.png' %} " class="house" alt="">
			
						<p class="icontitle">Houses &amp; Other Single Units:</p>

					
				
						{% for house in house_list %}
							<div class="house">
								<div class="houseListing">
								<a href="/listing/{{ house.id }}">{{ house.name }}</a>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
					
			</div>
		</div><!-- house list -->


		<div class="col-xs-6" style="width: 50.77%; margin-right: -23px; float: right;">
			<div class="row border">
				<img src=" {% static 'apartment.png' %} " class="apt" alt="">
				<p class="icontitle">Apartment Complex Listings:
					<div id="listings">
						{% for complex in complex_list %}
							<div class="complex" id="complex">
								{{ complex.name }}
								<div class="listing" id="complex{{ complex.id }}">
								{% for listing in complex.listing_set.all %}
									<a class="address" href="/listing/{{ listing.id }}">{{ listing.address }}</a>
									</br>
								{% endfor %}
								</div>
							</div>

						{% endfor %}
					</div>
			</div>
		</div>

		



	</div>
</div>
	

	
	


<div id="map">.</div>

</div>

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
	<script  async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDaKLjivuDKpR4yNtlz53u5B68-xq02VVU&libraries=places&callback=initMap"></script>
	


{% endblock mainblock %}

main/templates/detail_view.html
{% extends 'base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Testing two HTML</title>

	<link rel="stylesheet" type="text/css" href=" {% static 'css/detail_view.css' %} " ></head>

<body>
	{% block mainblock %}
	<div class="container-flow">

		<div>
			<!-- <h3>Listing for: {{ listing.complex_name.name }}</h3>
		-->
		<div class="row">

			<div class="col-xs-8">
				<img src="/{{ listing.upload_image }}" alt="your image" style="        box-shadow: 2px 3px 4px;
							border: 2px solid rgb(11, 11, 11);
							margin: -15px;
							width: 45%;">
				<p class="adeets">
					<br>
					<p id="address">
						{{ listing.address }}
						<br>{{ listing.city }}, {{ listing.state }}</p>
				</p>

				<hr class="hr"></div>
			<div class="col-xs-4">
				<img src="{% static "profile.png" %}" alt="" style="    border: 1px solid;
	border-radius: 115px;
	margin-top: 20px;
	width: 25%;
	margin-left: -60px;"	>
				<p class="deets" id="nam">{{ listing.name }}</p>
			</div>
			<div class="col-xs-8">
				<p class="deets" id="price">${{ listing.selling_price }}</p>
				<img src="{% static "home.png" %}" alt="" id="ic">
				<p class="deets" id="room">{{ listing.room_type }}</p>
				<img src="{% static "contract.png" %}" alt="" id="icontract">
				<p class="deets" id="contract">{{ listing.contract_length }}</p>
				<img src="{% static "furnish.png" %}" alt="" id="ifurnish">
				<p class="deets" id="furnish">{{ listing.furnishings_type }}</p>
				<p class="deets" id="available">{{ listing.availability_date }}</p>
				<hr class="hrs">
				<p class="deets" id="descrip"> <u>About this Listing</u>
					<br>
					<br>{{ listing.description }}</p>

				<br>
				<br>
				<br>
				<br>

				<p class="deets" id="amen">
					Amenities:
			{% if listing.amenity.all %}
				{% for amenity in listing.amenity.all %}
			{{ amenity.amenity }}
				</br>
				{% endfor %}
			{% else %}
			   no amenities
			{% endif %}
				<p class="deets">Number of Roommates:{{ listing.roommates}}</p>
				<p class="deets">Roommate Gender:{{ listing.gender_choices }}</p>

				<p class="deets">Building Type:{{ listing.building_type }}</p>

				<p class="deets">BYU Housing: {{ listing.BYU_housing }}</p>
				<p class="deets">Is it an Apartment Complex: {{ listing.apartment_complex }}</p>
				<p class="deets">Complex Name: {{ listing.complex_name }}</p>
				<p class="deets">Distance from BYU: {{ listing.distance_from_BYU  }}</p>
				<p class="deets">Distance from UVU: {{ listing.distance_from_UVU  }}</p>

			</div>
		</div>

		<br/>
		<br/>

	</div>

</div>
{% endblock mainblock %}
</body>

</html>

main/templates/list_detail.html
{% extends 'base.html' %}



<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Testing two HTML</title>

{% block mainblock %}

	<div class="">
		<h1>{{ complex.name }}</h1>
		<table class="table table-condensed">
			<thead>
				<tr>
					<th>Headline</th>
					<th>Address</th>
					<th>Distance to BYU</th>
					<th>Distance to UVU</th>
					<th>Selling Price</th>
				</tr>
			</thead>
			<tbody>
				{% for listing in listings %}
				
					<tr>
						<td>{{ listing.name }}</td>
						<td>{{ listing.address }}</td>
						<td>{{ listing.distance_from_BYU }}</td>
						<td>{{ listing.distance_from_UVU }}</td>
						<td>{{ listing.selling_price }}</td>
					</tr>

				{% endfor %}
			</tbody>
		</table>
		



	

	</div>

{% endblock mainblock %}

main/templates/post.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>





	<link class="jsbin" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
<meta charset=utf-8 />

<title>JS Bin</title>
<!--[if IE]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<style>
  article, aside, figure, footer, header, hgroup, 
  menu, nav, section { display: block; }
</style>





	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	

	
	<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" type="text/css" href="{% static "css/post.css" %}">
	
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery-1.11.3.min.js" %}"></script>
{{ form.media }}


</head>
<body>
	
<div class="container">
 <div class="row">
	<div class="title">Post a New Listing</div>
 </div>
<div class="row first">


<form action="/listingcreate/" method="POST" enctype="multipart/form-data" style="margin-top:20px; margin-left:15px">

	{% csrf_token %}
	{{ form|crispy }} 

	<input type='file' onchange="readURL(this);" />
    <img id="blah" src="#" alt="your image" />
	
	<input type="submit" Value="Create" class="sub" />

</form>
<br>
<br>
<div class="row">
   <div class="back" style="width:70%;">
	<a class="btn btn-primary bk" href="/" role="button" style="float:right;">Back</a>
   </div>
 </div>

</div>
</div>

</body>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
</html>

main/templates/testing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Testing HTML</title>
</head>

<body>

    {% for complex in complex_list %}

    <a href="/testing/{{ complex.id }}">{{ complex.name }}</a>
    </br>

    {% endfor %}

</body>

</html>